---
- name: Deploy python app via systemd and nginx
  hosts: vps
  become: true

  vars:
    # Динамически берет пользователя из параметров подключения SSH - vars.VPS_USER в GitHub
    app_user: "{{ ANSIBLE_REMOTE_USER }}"
    app_dir: "/home/{{ app_user }}/app/devopsimsya/py_app"
    venv_dir: "{{ app_dir }}/venv"

  tasks:
    # 1. Установка системных зависимостей для сборки C-расширений Python и работы веб-сервера
    - name: Install required system packages
      ansible.builtin.apt:
        name:
          - python3-venv
          - python3-pip
          - python3-dev # Заголовочные файлы Python (Python.h) для компиляции C-модулей
          - build-essential
          - rsync # нужна модулю synchronize
          - nginx
        state: present
        update_cache: true # выполняет аналог команды apt update
        cache_valid_time: 3600 # ansible проверяет: обновлялся ли кэш apt за последний час. Если да - пропуск пункта выше.

    # 2. Создание директорий приложения с правами пользователя
    - name: Create application directories
      # ansible.builtin.file заменяет собой сразу несколько bash-команд: mkdir, chmod, chown, ln -s, rm и touch
      ansible.builtin.file:
        # Путь к целевой папке на сервере. Значение подставляется динамически из списка в блоке loop на каждом шаге итерации
        path: "{{ item }}"
        state: directory
        # owner и group - аналог chown user:user /путь
        owner: "{{ app_user }}"
        group: "{{ app_user }}"
        mode: '0755' # магия чисел, которую забуду :(
      # Вообще луп нужен из-за приколов с правами. Если бы в path создавался сразу полный путь, то промежуточные папки
      # были бы созданы с правами root:root из-за become: true
      loop:
        - "/home/{{ app_user }}/app/devopsimsya"
        - "{{ app_dir }}"
        - "{{ app_dir }}/src"

    # 3. Синхронизация исходного кода через rsync (py_app/src -> VPS). Проще говоря пушим код с гитлаб раннера на VPS. 
    # Единственный таск с этого плейбука, который выполняется НЕ на моей ВПСке
    # ansible.posix.synchronize — это не самостоятельная программа, а удобная Python-обертка вокруг системной утилиты Linux rsync
    - name: Synchronize python source code
      ansible.posix.synchronize:
        # playbook_dir - встроенная переменна ansible
        # содержит абсолютный путь к папке, в которой физически лежит исполняемый .yaml
        src: "{{ playbook_dir }}/../py_app/src/"
        dest: "{{ app_dir }}/src/"
        recursive: true # - аналог утилиты rsync с флагом -r (или частью флага -a). указывает сканировать всю файловую структуру вглубь
        delete: true # флаг --delete утилиты rsync. удаляет на сервере те файлы, которых больше нет в репозитории
      become: false # lля synchronize директиву become необходимо принудительно отключить. 
      #А то раннер ГитХаба попытается войти на сервак по SSH как рут, у которого нету ключей или прав на прямой логин

    # 4. Создание venv и установка зависимостей из requirements.txt
    - name: Install Python dependencies in virtualenv
      ansible.builtin.pip:
        requirements: "{{ app_dir }}/src/requirements.txt"
        virtualenv: "{{ venv_dir }}"
        virtualenv_command: "python3 -m venv"
      become: true
      become_user: "{{ app_user }}" # если бы venv создавал root, то все скачанные библиотеки, бинарники (gunicorn, uvicorn) и кэш Python (site-packages/) принадлежали бы root:root
      notify: Restart Python Service # триггер для перезапуска службы devopsimsya-py из шага 5. Запускает одноименный Handler, прописанный внизу плейбука
      # триггерится на изменения зависимостей. Если ничего не менялось возвращает статус - ок

    # 5. Генерация файла службы devopsimsya.service из шаблона .j2 с подстановкой реальных путей
    # В отличие от обычного copy, который пересылает файл байт в байт, модуль template работает в два этапа:
    # Рендеринг на тачке гитхаб раннера: движок Jinja2 считывает файл .j2, находит все конструкции {{ app_user }}, {{ app_dir }}, {{ venv_dir }} и подставляет в них реальные значения переменных.
    # Передача готового файла на VPS: На сервер отправляется уже чистый текстовый конфиг, где нет никаких шаблонов — только итоговые абсолютные пути и системный пользователь.
    - name: Template and install systemd service unit
      ansible.builtin.template:
        src: "{{ playbook_dir }}/../conf/devopsimsya-py.service.j2"
        #Директория /etc/systemd/system/ — главное место в Linux для пользовательских и сторонних служб. Файлы здесь имеют 
        #высший приоритет над системными пакетами из /lib/systemd/system/. Имя файла определяет имя будущей службы: devopsimsya-py
        dest: /etc/systemd/system/devopsimsya-py.service
        #Службы systemd управляются ядром ОС и суперпользователем. Файл конфигурации службы обязан принадлежать root, 
        #чтобы обычный пользователь не мог отредактировать команду запуска и выполнить вредоносный код с повышенными привилегиями.
        owner: root
        group: root
        mode: '0644' #когда-нибудь я все запомню)
      notify:
        - Reload systemd daemon
        - Restart Python Service
      #Когда unit-файл меняется (например, изменился порт или флаги Gunicorn), требуется строгая последовательность из двух действий:
      #Reload systemd daemon (systemctl daemon-reload):
      #Linux кэширует все unit-файлы в оперативной памяти при старте системы. Если изменить файл на диске, systemd проигнорирует изменения и выдаст предупреждение. Этот хэндлер заставляет systemd перечитать конфигурацию с диска.
      #Restart Python Service (systemctl restart devopsimsya-py):
      #После того как systemd узнал о новой конфигурации, мы перезапускаем сам процесс приложения, чтобы он поднялся с новыми параметрами.

    # 6. Добавление конфигурации nginx и включение сайта через симлинк
    # Чтобы активировать сайт, в sites-enabled/ создается символическая ссылка (ярлык) на файл из sites-available/
    - name: Copy nginx configuration
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/../conf/devopsimsya-py.nginx"
        dest: /etc/nginx/sites-available/devopsimsya-py
        owner: root
        group: root
        mode: '0644'
      notify: Reload nginx

    - name: Enable nginx site via symlink
      ansible.builtin.file:
        src: /etc/nginx/sites-available/devopsimsya-py
        dest: /etc/nginx/sites-enabled/devopsimsya-py
        state: link
      notify: Reload nginx #используется reload, а не restart:
      #reload (Graceful reload): NGINX перечитывает файлы конфигурации на лету. Старые воркеры спокойно дообслуживают 
      #текущие запросы пользователей, а новые воркеры начинают принимать трафик по обновленным правилам. Нулевой даунтайм.

    # 7. Запуск службы и добавление в автозагрузку
    #фиксирует желаемое конечное состояние сервиса: приложение обязано быть запущено прямо сейчас 
    #и обязано автоматически подниматься после любой перезагрузки VPS
    - name: Ensure Python app is enabled and running
      ansible.builtin.systemd:
        #Расширение .service указывать не обязательно — Ansible и systemd подставляют его по умолчанию.
        name: devopsimsya-py # Имя службы, которой мы управляем. Ansible автоматически сопоставляет это имя с файлом /etc/systemd/system/devopsimsya-py.service из таска 5
        state: started # Аналог команды systemctl start devopsimsya-py
        enabled: true

  handlers:
    - name: Reload systemd daemon
      ansible.builtin.systemd:
        daemon_reload: true

    - name: Restart Python Service
      ansible.builtin.systemd:
        name: devopsimsya-py # имя сервису задается в таске 5
        state: restarted

    - name: Reload nginx
      ansible.builtin.systemd:
        name: nginx
        state: reloaded



