---
- name: Setup Docker and Host Environment
  hosts: all
  become: true

  vars:
    #compose V2, выставил ща в false, какой-то берд на vps происходит из-за того что уже был докер установлен
    docker_install_compose_plugin: false
    #убирает на всякий устаревший compose (docker-compose)
    docker_compose_package_state: absent
    docker_service_state: started
    docker_service_enabled: true

  pre_tasks:
    # сбрасываем ошибку failed state в systemd
    - name: Reset systemd failed state for docker units
      ansible.builtin.command: systemctl reset-failed docker.service docker.socket
      failed_when: false
      changed_when: false

    # включаем и запускаем сокет до вызова роли (были проблемы с тачкой, из-за того что там докцкер уже 90 дней живет и не обновлялся
    - name: Ensure docker.socket is running before service starts
      ansible.builtin.systemd:
        name: docker.socket
        state: started
        enabled: true
      ignore_errors: true

  roles:
    - role: geerlingguy.docker

  tasks:
    # 1. Создаем стандартный системный каталог для CLI-плагинов Docker
    - name: Ensure Docker CLI plugins directory exists
      ansible.builtin.file:
        path: /usr/local/lib/docker/cli-plugins
        state: directory
        mode: '0755'

    # 2. Скачиваем официальный бинарник Docker Compose напрямую
    - name: Download official Docker Compose CLI plugin
      ansible.builtin.get_url:
        url: "https://github.com/docker/compose/releases/latest/download/docker-compose-linux-{{ ansible_architecture }}"
        dest: /usr/local/lib/docker/cli-plugins/docker-compose
        mode: '0755'

    - name: Ensure project directory exists with correct ownership
      # тупо вышло, под рутом пакпка создалась и по пермишн крашнулся деплой
      ansible.builtin.file:
        path: /opt/devopsimsya
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0755'