- name: Configure Web Server
  hosts: vps          # К какой группе из inventory.ini применить
  become: true        # Выполнять задачи с правами sudo (root)

  tasks:
    - name: Ensure NGINX is installed
      ansible.builtin.apt:
        name: nginx
        state: present   # "present" = убедись, что пакет установлен; если уже есть — ничего не делай
        update_cache: true

    - name: Ensure NGINX service is running and enabled on boot
      ansible.builtin.systemd:
        name: nginx
        state: started   # systemctl start nginx
        enabled: true    # systemctl enable nginx