name: Install NGINX

on:
  workflow_dispatch:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      HOST: ${{ secrets.VPS_IP }}
      USER: ${{ variables.VPS_USER }}
      SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

    steps:
      - uses: actions/checkout@v4

      - name: Configure SSH Private Key
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

      - name: Add VPS Host to Known Hosts
        run: |
          ssh-keyscan -H "$HOST" >> ~/.ssh/known_hosts

      - name: Install NGINX
        run: |
          ssh -i ~/.ssh/id_ed25519 "$USER@$HOST" "sudo apt update && sudo apt install nginx -y"